### PR TITLE
49 config

### PR DESCRIPTION
**Pull request by edchapman88**
Move some config variables from crate lib.rs files to a single global .toml config file at the root of the trustchain directory.

### CODE REVIEW

**Comment by sgreenbury** [comment]
I think this is looking great but propose we modify with the following before merging:
- I think non-ignored tests should not depend on a `trustchain_config.toml` so no extra configuration is required to run the default tests
- However, ignored tests (e.g. mainly some integration tests requiring ION etc) can depend on a `trustchain_config.toml` as they already have this requirement
- Given the above we can remove the `TRUSTCHAIN_DATA` environment variable from the config and back into the lib
- A more natural place for `trustchain_config.toml` is in the `TRUSTCHAIN_DATA` path as opposed to the repo with the initial set-up setting `TRUSTCHAIN_DATA` and adding a default `trustchain_config.toml` to this location

**Comment by edchapman88** [comment]
I just wanted to keep a few notes to pass back on to you as I’m looking into these points:

  *   I’ve run the default tests with an empty TRUSTCHAIN_DATA environment variable to check that they all run without the `.trustchain_data` folder (which now includes `trustchain_config.toml` ).
  *   I found that I had to add `trustchain_core::chain::tests::test_print_chain` to the set of ignored tests because of its dependency on the `root_event_time_2378493`.
  *   One additional note: moving `trustchain_config.toml` into `.trustchain_data` introduces a dependency on the `TRUSTCHAIN_DATA` constant in the `trustchain_ion` crate, because the environment variable is required when the path to `trustchain_config.toml` is assembled. I don’t think this is a problem, just FYI.

From: Sam Greenbury ***@***.***>
Date: Friday, 31 March 2023 at 10:26
To: alan-turing-institute/trustchain ***@***.***>
Cc: Edward Chapman ***@***.***>, Author ***@***.***>
Subject: Re: [alan-turing-institute/trustchain] 49 config (PR #78)

I think this is looking great but propose we modify with the following before merging:

  *   I think non-ignored tests should not depend on a trustchain_config.toml so no extra configuration is required to run the default tests
  *   However, ignored tests (e.g. mainly some integration tests requiring ION etc) can depend on a trustchain_config.toml as they already have this requirement
  *   Given the above we can remove the TRUSTCHAIN_DATA environment variable from the config and back into the lib
  *   A more natural place for trustchain_config.toml is in the TRUSTCHAIN_DATA path as opposed to the repo with the initial set-up setting TRUSTCHAIN_DATA and adding a default trustchain_config.toml to this location

**Comment by edchapman88** [comment]
I just wanted to keep a few notes to pass back on to you as I’m looking into these points:
* I’ve run the default tests with an empty TRUSTCHAIN_DATA environment variable to check that they all run without the `.trustchain_data` folder (which now includes `trustchain_config.toml` ).
* I found that I had to add `trustchain_core::chain::tests::test_print_chain` to the set of ignored tests because of its dependency on the `root_event_time_2378493`.
* One additional note: moving `trustchain_config.toml` into `.trustchain_data` introduces a dependency on the `TRUSTCHAIN_DATA` constant in the `trustchain_ion` crate, because the environment variable is required when the path to `trustchain_config.toml` is assembled. I don’t think this is a problem, just FYI.

**Comment by sgreenbury** [comment]
> I just wanted to keep a few notes to pass back on to you as I’m looking into these points:

Thanks!

>     * I’ve run the default tests with an empty TRUSTCHAIN_DATA environment variable to check that they all run without the `.trustchain_data` folder (which now includes `trustchain_config.toml` ).

Great and FYI we set `TRUSTCHAIN_DATA` for tests that need it when we call the `init()` function for the non-ignored tests that need it.

>     * I found that I had to add `trustchain_core::chain::tests::test_print_chain` to the set of ignored tests because of its dependency on the `root_event_time_2378493`.

This is a good idea for now. We've discussed this previously as the timestamp is not part of the chain and we only want to set it in a chain (if it should be there at all) if it's during a verification. There is a PR #81 potentially including this that would allow us to remove the ignore again.

>     * One additional note: moving `trustchain_config.toml` into `.trustchain_data` introduces a dependency on the `TRUSTCHAIN_DATA` constant in the `trustchain_ion` crate, because the environment variable is required when the path to `trustchain_config.toml` is assembled. I don’t think this is a problem, just FYI.

Yes agreed this seems fine as we can import the constant from `trustchain-core`.

One other thought is that we could rename `trustchain_config.toml` as `config.toml` given it is already in `TRUSTCHAIN_DATA`.

**Pull request merged**
