### PR TITLE
102 refactor verifiable timestamp

### PR DESCRIPTION
**Pull request by thobson88**
Addresses #102.

### CODE REVIEW

**Comment by thobson88** [comment]
Unit tests all pass but I haven't run the integration tests yet.

**Comment by sgreenbury** [comment]
This looks great, nice one! I've tried the integration tests, a couple of fails:
- test trustchain_verification
- test test_verifiable_timestamp

It looks like the [`timestamp_commitment().hash()`](https://github.com/alan-turing-institute/trustchain/blob/102-refactor-verifiable-timestamp/trustchain-ion/tests/verifier.rs#L57) call is not be producing the [expected hash](https://github.com/alan-turing-institute/trustchain/blob/102-refactor-verifiable-timestamp/trustchain-ion/tests/verifier.rs#L46).

**Comment by thobson88** [comment]
Would be good to address #104 in here too.

**Comment by sgreenbury** [comment]
Since #106 is merged and all tests pass, this is ready to merge.

**Pull request merged**
